### ISSUE TITLE
Minimal Basisset Issues

### ISSUE THREAD

**Issue by awvwgk** [clavigne/xtb-hacks#1]
Interesting project, may I offer some unsolicited advice here? Extended tight binding uses normally a minimal basis set together with the basic assumption of the basis functions on a center being orthonormal.

Adding more (polarisation or diffuse) functions on a center is difficult, because they are a lot of things that have to be taken care of. There is the obvious difficulty of actually defining the matrix elements (self energies or atomic levels in `lev`), they represent the *diagonal* elements of the solved atoms. This requires any additional function to be orthonormal to the existing basis functions, it happens that additional functions are not automatically orthonormalized in `xtb`, which results in an ill-defined starting point for the tight binding calculation if functions are added.

I guess `xtb` will produce some result even with an ill-defined basisset, but I doubt that this results will be meaningful at all.

**Comment by clavigne** [comment]
Hi Sebastian!

Yes so this was mostly just an experiment to see if it was even possible to add orbitals. I am aware of the issue with orthonormalization, and that the results are therefore complete crap :D  Due to time constraints I haven't explored it further. As I understand it, including additional basis function would likely require a global reparametrization, and so it's not exactly trivial.

(By the way, the idea was to improve some of the physics viz anions. Not sure how much of a difference adding basis functions would make though...)

By the way, this makes me think, is there any plan to release the xtb parameter optimization code? I assume you guys have an internal way of optimizing parameter values and testing the result on a standardized set of molecules. It would be really interesting to play with. (I also understand not releasing that part.)

Thanks a lot for your interest!
Cyrille

**Comment by awvwgk** [comment]
In principle yes, you can add orbitals, but you have to tell the program how to deal with them first. Have a look at the `param_ipea-xtb.txt`, it adds diffuse s-functions to improve the description of electron affinities (capital S instead of small s). See https://github.com/grimme-lab/xtb/blob/db14a9e/param_ipea-xtb.txt#L121.

And you also have to define the additional matrix elements with `kdiff` in the global parameters (at least for GFN2-xTB it is not defined). See https://github.com/grimme-lab/xtb/blob/db14a9e/param_ipea-xtb.txt#L10. Also, if you compare the IPEA-xTB and with the GFN1-xTB you will notice that the parameters only differ slightly.

In the end those additional functions will cause more problems (BSSE) than they help. So yes, one should try to improve the physics. Something we tried, and I guess we were somewhat successful with it, was adding higher moments to the electrostatics.

I'm not the one to decide if the fitset will be released.

**Comment by clavigne** [comment]
Thanks for the pointers! Will look into it.

**Comment by awvwgk** [comment]
Good luck with this. The issue can probably be closed now.
